# =============================================================================
# DEFINICIÓN DE VARIABLES DE APLICACIONES
# =============================================================================
$mainMod = SUPER
$terminal = wezterm
$menu = rofi -show drun
$fileManager = dolphin