# =============================================================================
# REGLAS DE VENTANAS
# =============================================================================
windowrule = float 1, match:class ^(org\.pulseaudio\.pavucontrol)$
windowrule = size 600 400, match:class ^(org\.pulseaudio\.pavucontrol)$
windowrule = move 65% 5%, match:class ^(org\.pulseaudio\.pavucontrol)$