--------------------------------------------------------------------------------
-- Hyprland Configuration
--
-- Entry point
--
-- Hyprland v0.55+
-- https://wiki.hypr.land
--
-- Toda la configuración está dividida en módulos para facilitar el
-- mantenimiento y mantener cada archivo enfocado en una única responsabilidad.
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Marca esta configuración como propia para eliminar el aviso amarillo que
-- aparece con el archivo autogenerado.
--------------------------------------------------------------------------------
package.path = package.path .. ";" .. os.getenv("HOME") .. "/.config/hypr/?.lua"
hl.config({
    autogenerated = false,
})

--------------------------------------------------------------------------------
-- CONFIGURATION
--------------------------------------------------------------------------------

require("modules.system")
require("modules.applications")
require("modules.autostart")
require("modules.appearance")
require("modules.input")
require("modules.windowrules")
require("modules.bindings")
require("modules.workspaces")