--------------------------------------------------------------------------------
-- Hyprland Configuration - Entry point (Hyprland v0.55+)
--------------------------------------------------------------------------------

-- Indicarle a Lua dónde buscar tus módulos dentro de la carpeta local
package.path = package.path .. ";" .. os.getenv("HOME") .. "/.config/hypr/?.lua"

-- Quitar el aviso amarillo de config autogenerada
hl.config({
    autogenerated = false,
})

--------------------------------------------------------------------------------
-- Carga de Módulos Modulares
--------------------------------------------------------------------------------
require("modules.system")
require("modules.applications")
require("modules.autostart")
require("modules.input")
require("modules.windowrules")
require("modules.appearance")
require("modules.bindings")
require("modules.workspaces")