# =====================
# MONITOR
# =====================

monitor=,preferred,auto,1

# =====================
# PROGRAMAS
# =====================

$terminal = wezterm
$menu = walker

# =====================
# AUTOSTART
# =====================

exec-once = waybar
exec-once = swaync
exec-once = hyprpaper

# =====================
# APARIENCIA
# =====================

general {
    gaps_in = 5
    gaps_out = 10

    border_size = 2

    resize_on_border = true

    layout = dwindle
}

decoration {
    rounding = 8

    blur {
        enabled = true
        size = 5
        passes = 2
    }
}

animations {
    enabled = true
}

# =====================
# INPUT
# =====================

input {
    kb_layout = us

    follow_mouse = 1

    touchpad {
        natural_scroll = true
    }
}

# =====================
# DWINDLE
# =====================

dwindle {
    pseudotile = true
    preserve_split = true
}

# =====================
# TECLAS
# =====================

$mainMod = SUPER

bind = $mainMod, RETURN, exec, $terminal
bind = $mainMod, SPACE, exec, $menu

bind = $mainMod, Q, killactive
bind = $mainMod SHIFT, E, exit

bind = $mainMod, F, fullscreen

# mover foco
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d

# mover ventanas
bind = $mainMod SHIFT, H, movewindow, l
bind = $mainMod SHIFT, L, movewindow, r
bind = $mainMod SHIFT, K, movewindow, u
bind = $mainMod SHIFT, J, movewindow, d

# workspaces
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5

bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5

# screenshot
bind = , PRINT, exec, grim -g "$(slurp)" ~/Pictures/screenshot.png