background {
    monitor =
    path = screenshot # Toma una captura de tu pantalla actual y le aplica el blur de abajo
    blur_passes = 3
    blur_size = 8
    color = rgba(15, 15, 15, 1.0)
}

# HORA
label {
    monitor =
    text = cmd[update:1000] echo "$TIME"
    color = rgba(242, 242, 242, 0.75)
    font_size = 90
    font_family = Iosevka Nerd Font Thin
    position = 0, 200
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 250, 50
    outline_thickness = 1
    dots_size = 0.2
    dots_spacing = 0.4
    dots_center = true
    outer_color = rgba(68, 68, 68, 1.0)
    inner_color = rgba(20, 20, 20, 0.6)
    font_color = rgb(200, 200, 200)
    fade_on_empty = true
    placeholder_text = <i>Ingresar contraseña...</i>
    hide_input = false
    position = 0, -50
    halign = center
    valign = center
}