general {
    # Evita lanzar múltiples instancias de Hyprlock
    lock_cmd = pidof hyprlock || hyprlock

    # Bloquear antes de suspender (por si algún día activas suspensión)
    before_sleep_cmd = loginctl lock-session

    # Encender monitores al volver de suspensión
    after_sleep_cmd = sleep 1 && hyprctl dispatch dpms off
}

# ==========================================
# BLOQUEO DE PANTALLA
# ==========================================
# timeout en segundos
# 18000 = 5 horas
listener {
    timeout = 18000
    on-timeout = loginctl lock-session
}

# ==========================================
# APAGADO DE MONITOR
# ==========================================
# 21600 = 6 horas
listener {
    timeout = 21600
    on-timeout = sleep 1 && hyprctl dispatch dpms off
    on-resume = sleep 1 && hyprctl dispatch dpms off
}

# ==========================================
# SUSPENSIÓN AUTOMÁTICA
# ==========================================
# Actualmente DESACTIVADA.
#
# Ejemplos:
#
# 1800  = 30 min
# 3600  = 1 hora
# 7200  = 2 horas
#
# listener {
#     timeout = 1800
#     on-timeout = systemctl suspend
# }
#
# ==========================================