# =============================================================================
# AUTOSTART (Servicios en segundo plano)
# =============================================================================
exec-once = waybar
exec-once = swaync
exec-once = awww-daemon & sleep 0.2 && ~/wallpapers_loop.sh &
exec-once = hypridle
exec-once = /usr/lib/polkit-kde-authentication-agent-1

# Daemons de escucha para el portapapeles
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store