# =============================================================================
# CONFIGURACIÓN DE HARDWARE & MONITORES
# =============================================================================

# Configuración del monitor Ultrawide ASUS 34" a 165Hz
monitor = DP-1, 3440x1440@165, 0x0, 1, bitdepth, 10

# Parámetros críticos para el driver propietario de NVIDIA
env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

misc {
    # VRR/Freesync desactivado por variaciones de brillo en escritorio (ASUS VG34VQL3A)
    vrr = 2
    mouse_move_enables_dpms = true
    key_press_enables_dpms = true
}

opengl {
    nvidia_anti_flicker = true
}

cursor {
    no_hardware_cursors = true
}